#!/usr/bin/env bash

sudo apt-get update

project_root="$(git rev-parse --show-toplevel)"
consul_version="0.4.1"

# go (consul-template requires 1.2)
sudo apt-get -y install bzr
cd $GOPATH
go get launchpad.net/godeb
$GOPATH/bin/godeb --help
sudo apt-get -y remove golang
sudo apt-get -y autoremove
$GOPATH/bin/godeb install


# Haproxy
sudo apt-get -y install haproxy


# Docker
sudo apt-get -y install docker.io
ln -sf /usr/bin/docker.io /usr/local/bin/docker
sed -i '$acomplete -F _docker docker' /etc/bash_completion.d/docker.io


# Consul
cd $project_root/assets
wget https://dl.bintray.com/mitchellh/consul/"$consul_version"_linux_amd64.zip
unzip "$consul_version"_linux_amd64.zip
rm "$consul_version"_linux_amd64.zip
cd $project_root
mkdir -p bin
ln -s assets/consul bin/consul
ln -s bin/consul ~/bin/consul

# Consul UI
cd $project_root/assets
wget https://dl.bintray.com/mitchellh/consul/"$consul_version"_web_ui.zip
unzip "$consul_version"_web_ui.zip
rm "$consul_version"_web_ui.zip
cd $project_root

# Registrator
sudo docker pull progrium/registrator

# Consul-Template
cd $project_root/bin
git clone https://github.com/hashicorp/consul-template.git
mv consul-template .consul-template
cd .consul-template
make
ln -s $project_root/bin/.consul-template/bin/consul-template $project_root/bin/consul-template

# Default haproxy config
cp haproxy.cfg.default build/haproxy.cfg

echo -e "\n\nBuild Successful"

